### PR TITLE
Added line duplication command

### PR DESCRIPTION
**Pull request by bovacu**
This PR adds a new command to duplicate the current line the cursor is at

### CODE REVIEW

**Review by travisdoor — CHANGES_REQUESTED** [review]
Hi, thanks for the PR. It's good for the first time and in the code, almost without documentation! 
One issue: your command does not work in an empty file. I tried to figure out a proper solution, and I suggest something like this.
[duplicate-line.patch](https://github.com/travisdoor/tine/files/13604380/duplicate-line.patch)

Step-by-step:

- Jump line begin
- Start the selection
- Jump line end
- Copy selection (I slightly changed the copy_selection to return if there was something selected)
- Insert newline character (there is already `insert_new_line`, but it turned out to be commonplace to do something like "commit", I have to rename it and make a simple function to just insert a new line).
- paste selection if it's not empty
- jump to the beginning of the indentation.

There was also one issue, the `paste` function is implicitly recorded as a single undo action; in this case, we want to group it together with a new line (so `paste` is also a bit tweaked).

**Comment by travisdoor** [comment]
You can use the patch directly, but maybe it's a good opportunity to explore the code-base.

**Comment by bovacu** [comment]
Hi! So I reviewed your patch and made sense to me, so I have applied it to the PR. I have been messing around the code base for a few days now, maybe a week and I've added some other features that I are useful to me, some of them are:

- Automatic completion of braces, parenthesis, brackets, single quotes and double quotes
- Showing the line number on the left side of each opened split
- Switching between splits with Alt+ArrowLeft/Right

If you find any of them useful or you think they could fit the original version of Tine, just let me know and I'll make the PRs!

**Comment by travisdoor** [comment]
Nice! 

`Automatic completion of braces, parenthesis, brackets, single quotes and double quotes` I personally don't use this much, but it can be optional.
`Showing the line number on the left side of each opened split` Same for this one, I guess a lot of people are using it.
`Switching between splits with Alt+ArrowLeft/Right` Is this just a remapping of default keys for the `other-split` command?

**Comment by bovacu** [comment]
I think you are right on this one `Switching between splits with Alt+ArrowLeft/Right` maybe it is just a remapping but I did implement the feature because I did not know about the `other-split` hahaha, but well, forced me to navigate more the code base

**Comment by bovacu** [comment]
One extra thing, I've seen on your patch (and tested) that you removed the `clear_selection(buf);` at the end of the `paste` function. This gave a bug where when you paste something, the selection won't go away. This is particularly annoying on the search bar as to remove the selection the 'esc' must be pressed and this also closes the search bar, I'll be commiting the fix now.

**Pull request merged**
